#### Doc 
https://medium.com/analytics-vidhya/understanding-principle-component-analysis-pca-step-by-step-e7a4bb4031d9

In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import plotly.graph_objects as go

In [2]:
# Read dataset
df = pd.read_csv("../data/fuel_consumption/Fuel_Consumption_Ratings.csv") # changed index_col
df.head()

Model Year   Make              Model Vehicle Class  Engine Size  Cylinders  \
0        2022  Acura                ILX       Compact          2.4          4   
1        2022  Acura         MDX SH-AWD    SUV: Small          3.5          6   
2        2022  Acura         RDX SH-AWD    SUV: Small          2.0          4   
3        2022  Acura  RDX SH-AWD A-SPEC    SUV: Small          2.0          4   
4        2022  Acura         TLX SH-AWD       Compact          2.0          4   

  Transmission Fuel  Fuel Consumption City  Fuel Consumption Hwy  \
0          AM8    Z                    9.9                   7.0   
1         AS10    Z                   12.6                   9.4   
2         AS10    Z                   11.0                   8.6   
3         AS10    Z                   11.3                   9.1   
4         AS10    Z                   11.2                   8.0   

   Fuel Consumption  Fuel Consumption Comb_mpg  CO2 Emissions  CO2 Rating  \
0               8.6                         33            200           6   
1              11.2                         25            263           4   
2               9.9                         29            232           5   
3              10.3                         27            242           5   
4               9.8                         29            230           5   

   Smog Rating  
0            3  
1            5  
2            6  
3            6  
4            7

In [3]:
df1 = df[["Engine Size","Cylinders","Fuel Consumption City","Fuel Consumption Hwy","Fuel Consumption","Fuel Consumption Comb_mpg","CO2 Emissions"]]
# Scale data before applying PCA
scaling=StandardScaler()
 
# Use fit and transform method 
scaling.fit(df1)
Scaled_data=scaling.transform(df1)

In [4]:
Scaled_data

array([[-0.58736541, -0.87138956, -0.76592053, ..., -0.87689859,
         0.76045331, -0.92840858],
       [ 0.21605563,  0.16301321,  0.01492958, ...,  0.02364703,
        -0.28092746,  0.04462041],
       [-0.87951851, -0.87138956, -0.44779641, ..., -0.42662578,
         0.23976293, -0.43417163],
       ...,
       [-0.87951851, -0.87138956, -0.44779641, ..., -0.42662578,
         0.23976293, -0.43417163],
       [-0.87951851, -0.87138956, -0.30319454, ..., -0.35735304,
         0.10959033, -0.37239201],
       [-0.87951851, -0.87138956, -0.04291117, ..., -0.11489845,
        -0.15075486, -0.12527354]])

In [5]:
# Set the n_components=1
principal=PCA(n_components=2)
principal.fit(Scaled_data)
x=principal.transform(Scaled_data)

In [6]:
principal.components_

array([[ 0.3548312 ,  0.35626417,  0.39538592,  0.3784573 ,  0.39641806,
        -0.36803194,  0.39372062],
       [ 0.58641482,  0.58771207, -0.08897901, -0.30916827, -0.17103019,
         0.40293521, -0.12490713]])

In [7]:
# check how much variance is explained by each principal component
print(principal.explained_variance_ratio_)

[0.88495027 0.07254584]


In [8]:
principal.explained_variance_

array([6.20114523, 0.50835322])